AllCops:
  Includes:
    - Rakefile
Documentation:
  Enabled: false
# Renaming `has_something?` to `something?` obfuscates whether it is a "is-a" or
# # a "has-a" relationship.
Style/PredicateName:
  Enabled: false
MethodLength:
  Max: 50
Metrics/LineLength:
  Max: 100
